//---------------------------

package minijam;

//---------------------------

import java.awt.Color;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.JButton;
import shape.CAxes;
import shape.COctagon;
import shape.CShapeBase;
import shape.CShapeStyle;
import shape.CStar;
import util.CVector;
import shape.Hexagon;
import shape.CTriangle;
import javax.swing.BorderFactory;
import javax.swing.JButton;

//---------------------------

public class CMainForm extends javax.swing.JFrame {
    
    public CMainForm() {
        
        Container c = this.getContentPane();
        c.setPreferredSize(Settings.WindowSize);
        c.setBackground(Settings.BackgroundColor);

        this.setTitle(Settings.Tittle + " [" + Settings.Version + "]");
        this.setResizable(Settings.IsResizableWindow);
        this.pack();
        
        initComponents();
        initCustomComponents();
        initKeyListener();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                m_isDraw = false;
                try {
                    m_thread.join();
                } catch(InterruptedException e) {
                    Log.error(this, e.getMessage());
                }
                
                Log.print(this, "exit");
            }
        });
        
        Log.print(this, "init form.");
    }
    
    //---------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //---------------------------

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                Log.print(this, "start thread");
                
                CMainForm form = new CMainForm();
                form.setVisible(true);
            }
        });
    }
    
    //---------------------------
    
    public Render getRender() {
        return m_render;
    }
    
    //---------------------------    
    
    private void update() throws InterruptedException {
        
        m_isDraw = true;
        m_toolkit = Toolkit.getDefaultToolkit();
        
        long frameTime = 1000L / 60;
        
        while(m_isDraw) {
            long start = System.currentTimeMillis();
            
            m_render.update();
            m_render.repaint();

            m_toolkit.sync();
            
            long    elapsed = System.currentTimeMillis() - start,
                    sleep = frameTime - elapsed;
            
            if(sleep > 0) {
                try {
                    Thread.sleep(sleep); 
                } catch (InterruptedException ignored) {  }
            }
        }
    }
    
    //---------------------------
    
    private void initCustomComponents() {
        
        Log.print(this, "init custom components.");
        
        //init render
        m_render = new Render();
        m_render.setSize(Settings.WindowSize);
        m_render.setBackground(Settings.RenderColor);
        
        m_render.setLayout(null);
        
        //Axes shape
        CShapeBase shape = new CAxes();
        shape.setSize(new CVector(  Settings.WindowSize.width, 
                                    Settings.WindowSize.height));
        
        shape.setStyle(new CShapeStyle(Color.YELLOW, new Color(0,0,0,0), 2));
        
        m_render.addShape(shape);
        
        //hexagon shape
        CShapeBase hexagon = new Hexagon();
        hexagon.setSize(new CVector(130, 130));        
        hexagon.setPosition(new CVector(900, 440));
        hexagon.setStyle(new CShapeStyle(Color.PINK, Color.WHITE, 1));

        m_render.addShape(hexagon);
        
        //button for hexagon
        JButton btnToggleVisibility = new JButton("Hide Hexagon");
        btnToggleVisibility.setName("btn_hexagon");
        btnToggleVisibility.setBounds(1060, 670, 200, 30);
        btnToggleVisibility.setBackground(Color.white);

        btnToggleVisibility.addActionListener(e -> {
            if (hexagon.getStyle().Color.getAlpha() == 0) {
                hexagon.setStyle(new CShapeStyle(Color.PINK, Color.WHITE, 1));
                btnToggleVisibility.setText("Hide Hexagon");
            } else {
                Color transparent = new Color(0, 0, 0, 0);
                hexagon.setStyle(new CShapeStyle(transparent, transparent, 0));
                btnToggleVisibility.setText("Show Hexagon");
            }
            m_render.repaint();
        });
        
        m_render.add(btnToggleVisibility);
        
        //shape star
        CVector size = new CVector(200, 200);
        CVector size_star = new CVector(70, 70);

        CStar star = new CStar();
        star.setSize(size_star);
        star.setOrigin(new CVector(size_star.x/2, size_star.y/2));
        star.setPosition(new CVector(Settings.WindowSize.width/4, 
                                        Settings.WindowSize.height/2 
                                                + Settings.WindowSize.height/5));
        
        star.setStyle(new CShapeStyle(new Color(135, 220, 125), 
                new Color(75, 120, 75), 3));
        
        m_render.addShape(star);
        CVector size_but = new CVector(200, 30);
                
        JButton btnStar = new JButton("Start animation");
        btnStar.setBounds(   Settings.WindowSize.width/4 - size_but.x/2, 
                                Settings.WindowSize.height 
                                                - Settings.WindowSize.height/8 + size_but.y/2,
                                size_but.x,
                                size_but.y);
        btnStar.setName("btn_star_animation");
        btnStar.setBackground(new Color(135, 220, 125));
        btnStar.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(75, 120, 75), 5),
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        
        btnStar.addActionListener(e -> {
            btnStar.setText(!star.getStateAnimation() ? "Stop animation" : "Start animation");
            star.setStateAnimation(!star.getStateAnimation());
        });
        
        m_render.add(btnStar);
        
        //shape octagon
        
        COctagon octagon = new COctagon();
        octagon.setSize(size);
        octagon.setBaseSize(octagon.getSize());
        octagon.setOrigin(new CVector(size.x/2, size.y/2));
        octagon.setPosition(new CVector(Settings.WindowSize.width/4, 
                                        Settings.WindowSize.height/4));
        
        octagon.setStyle(new CShapeStyle(new Color(51, 51, 51), Color.BLACK, 4));
        
        m_render.addShape(octagon);
        
        //octagon button
        size.x = 200;
        size.y = 30;
                
        JButton btnOctagon = new JButton("Start animation");
        
        btnOctagon.setName("btn_octagon_animation");
        btnOctagon.setBounds(   Settings.WindowSize.width/4 - size.x/2, 
                                Settings.WindowSize.width/4 - size.y/2,
                                size.x,
                                size.y);
        
        btnOctagon.setBackground(new Color(0,0,0,0));
        btnOctagon.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLUE, 2),
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        
        btnOctagon.addActionListener(e -> {
            btnOctagon.setText(!octagon.getStateAnimation() ? "Stop animation" : "Start animation");
            octagon.setStateAnimation(!octagon.getStateAnimation());
        });
        
        m_render.add(btnOctagon);
        
        //triangle
        CShapeBase triangle = new CTriangle();
        triangle.setSize(new CVector(100, 80));        
        triangle.setPosition(new CVector(900, 150));
        triangle.setStyle(new CShapeStyle(Color.RED, Color.BLACK, 2));

        m_render.addShape(triangle);
        
        //triangle button
        JButton btnTriangleColor = new JButton("Change color");
        btnTriangleColor.setName("btn_triangle_color");
        btnTriangleColor.setBounds(850, 240, 200,30);
        btnTriangleColor.setBackground(Color.white);
        
        
        btnTriangleColor.addActionListener(e -> {
            if (triangle != null) {
                Color current = triangle.getStyle().Color;
                Color next = current.equals(Color.RED) ? Color.BLUE : Color.RED;
                triangle.setStyle(new CShapeStyle(next, Color.BLACK, 2));
                m_render.repaint();
            }
        });
        m_render.add(btnTriangleColor);
        
        //init render
        this.add(m_render);
    
        Runnable task = () -> {
            try {
                this.update();
            } catch(InterruptedException e) {
                Log.error(this, e.getMessage());
            }
        };
        
        m_thread = new Thread(task);
        m_thread.start();
    }
    
    //---------------------------
    
    private void initKeyListener() {
        InputMap im = m_render.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = m_render.getActionMap();
        
        im.put(KeyStroke.getKeyStroke("ESCAPE"), "exitAction");
        
        am.put("exitAction", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CMainForm.this.dispatchEvent(new WindowEvent(CMainForm.this, WindowEvent.WINDOW_CLOSING));  
            }
        });
    }
    //---------------------------

    private Render m_render;
    private Toolkit m_toolkit;
    
    Thread m_thread;
    
    private boolean m_isDraw;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
