/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minijam;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import shape.COctagon;

class OctagonTest {
    @Test void appHasAGreeting() {
        
        COctagon octagon = new COctagon();
        
        boolean testState = true;
        
        octagon.setStateAnimation(testState);
        assertEquals(testState, octagon.getStateAnimation());
    }
}
